import { chromium } from "playwright";
import fs from "node:fs";
const base = "http://127.0.0.1:8765/?v=v34-ig-completion";
const browser = await chromium.launch({ headless: true });
const findings = [], errors = [];
function check(value, message){findings.push({pass:!!value,message}); if(!value)throw Error("FAIL: "+message)}
async function click(page, selector){await page.locator(selector).first().click({timeout:10000})}
async function nav(page, route){await click(page, '.mp-header-nav nav [data-view="'+route+'"]');await page.locator('#mrRouteView[data-route="'+route+'"]').waitFor()}
async function checkReelAlignment(page,label){
 const r=await page.locator('#mrRouteView .mr-instagram-gallery>.mr-ig-tile').evaluateAll(cards=>cards.map(card=>{
  const box=card.getBoundingClientRect();
  const actions=card.querySelector('.mr-ig-tile-actions');
  const name=card.querySelector('.mr-ig-under>b');
  return {top:box.top,bottom:box.bottom,actionsBottom:actions?.getBoundingClientRect().bottom,
   actionsTop:actions?.getBoundingClientRect().top,nameHeight:name?.getBoundingClientRect().height};
 }));
 const rows=[];
 for(const item of r){let group=rows.find(group=>Math.abs(group[0].top-item.top)<2);if(group)group.push(item);else rows.push([item]);}
 const within=(arr,key,eps)=>Math.max(...arr.map(x=>x[key]))-Math.min(...arr.map(x=>x[key]))<=eps;
 const align=rows.every(row=>within(row,'bottom',2)&&within(row,'actionsTop',2)&&within(row,'actionsBottom',2)&&within(row,'nameHeight',2));
 check(r.length===5&&align,label+" per-row card bottoms, names and button baselines align");
}
async function run(){
 const source=JSON.parse(fs.readFileSync("data/instagram-electronics.json","utf8"));
 const context=await browser.newContext({viewport:{width:1440,height:900},permissions:["clipboard-read","clipboard-write"]});
 const page=await context.newPage();
 page.on("pageerror", e => errors.push(e.message));
 // Keep initial empty-state QA separate from published real research data.
 const emptyResearch={schema:"mozzipick.chat-reports.v1",reports:{"1":[],"1-1":[],"1-2":[],"1-3":[]}};
 await page.route("**/data/command-reports.json*",r=>r.fulfill({status:200,contentType:"application/json",body:JSON.stringify(emptyResearch)}));
 await page.goto(base, {waitUntil:"domcontentloaded"});
 await page.locator("#mrHomeDashboard .mr-card").first().waitFor({timeout:20000});
 check(await page.locator("#mrHomeDashboard .mr-card").count()>=4,"Homepage product cards load");
 const css=await page.locator('link[href*="v33.css"]').last().getAttribute("href");
 check(css?.includes("v35-detail-command-r23"),"V3.5 product-detail command stylesheet linked");
 await nav(page,"categories");
 check(await page.locator('#mrRouteView [data-sort-order] option').count()===3,"Category sort options");
 await page.locator('#mrRouteView [data-sort-order]').selectOption("등급순");
 check(await page.locator('#mrRouteView .mr-card').count()===5,"Category five-item pagination");
 const clipped=await page.locator('#mrRouteView .mr-card').evaluateAll(cards=>cards.some(card=>{const a=card.querySelector('.mr-card-actions');return a&&a.getBoundingClientRect().bottom>card.getBoundingClientRect().bottom+2}));
 check(!clipped,"Category action buttons not clipped");
 await click(page,'#mrRouteView .mr-card [data-detail]');
 await page.locator('#mrRouteView .mr-detail-page').waitFor();
 check(await page.locator('#mrRouteView [data-copyword]').count()===4,"Product detail four search keywords");
 const productBefore=await page.locator('#mrRouteView .mr-detail-summary h1').innerText();
 check(await page.evaluate(()=>/^detail:/.test(history.state?.mozzipick||"")),"Opening product detail adds dedicated browser history entry");
 await click(page,'#mrRouteView .mr-detail-quick [data-command="2"]');
 await page.locator('#mrCommandView .mr-command-return [data-return-product]').waitFor();
 check((await page.locator('#mrCommandView .mr-command-selected strong').innerText())===productBefore,"Detail command uses exact selected product");
 await page.evaluate(()=>history.back());
 await page.locator('#mrRouteView .mr-detail-page').waitFor();
 check(await page.evaluate(()=>/^detail:/.test(history.state?.mozzipick||"")),"Browser back from command restores detail history entry");
 check((await page.locator('#mrRouteView .mr-detail-summary h1').innerText())===productBefore,"Browser back restores exact original product detail");
 await page.evaluate(()=>history.forward());
 await page.locator('#mrCommandView [data-return-product]').waitFor();
 check((await page.locator('#mrCommandView .mr-command-selected strong').innerText())===productBefore,"Browser forward restores command bound to the same product");
 await click(page,'#mrCommandView [data-return-product]');
 await page.locator('#mrRouteView .mr-detail-page').waitFor();
 await click(page,'#mrRouteView .mr-detail-quick [data-command="2"]');
 check((await page.locator('#mrCommandView .mr-generated').innerText()).includes("나도"),"Detail script includes complete comment CTA");
 await page.locator('#mrCommandView input[name="mr-script-format"][value="리뷰형"]').check();
 check((await page.locator('#mrCommandView .mr-generated').innerText()).includes("선택 형식: 리뷰형"),"Detail script option produces selected review draft");
 for(const n of [1,3,4,5]){
  await click(page,'#mrCommandView .mr-command-quick [data-command="'+n+'"]');
  check((await page.locator('#mrCommandView .mr-generated').innerText()).includes(productBefore),"Detail command "+n+" retains selected product");
 }
 check((await page.locator('#mrCommandView .mr-generated').innerText()).includes("링크 미확인")||await page.locator('#mrCommandView .mr-generated').innerText().then(x=>x.includes("coupang.com")),"Detail DM does not invent product link");
 await click(page,'#mrCommandView [data-return-product]');
 await page.locator('#mrRouteView .mr-detail-page').waitFor();
 check((await page.locator('#mrRouteView .mr-detail-summary h1').innerText())===productBefore,"Return from command restores original detail");
 check(await page.evaluate(()=>/^detail:/.test(history.state?.mozzipick||"")),"Command return lands on detail history entry");
 await page.evaluate(()=>history.back());
 await page.locator('#mrRouteView [data-sort-order]').waitFor();
 check(await page.evaluate(()=>history.state?.mozzipick==="route:categories"),"Browser back from detail restores original category URL state");
 check(await page.locator('#mrRouteView [data-sort-order]').inputValue()==="등급순","Browser back restores category sort");
 await page.evaluate(()=>history.forward());
 await page.locator('#mrRouteView .mr-detail-page').waitFor();
 check((await page.locator('#mrRouteView .mr-detail-summary h1').innerText())===productBefore,"Browser forward restores the original detail");
 await page.evaluate(()=>history.back());
 await page.locator('#mrRouteView [data-sort-order]').waitFor();
 await click(page,'#mrRouteView .mr-card [data-detail]');
 await click(page,'#mrRouteView [data-detail-back]');
 await page.locator('#mrRouteView [data-sort-order]').waitFor();
 check(await page.evaluate(()=>history.state?.mozzipick==="route:categories"),"On-page detail back restores original history entry");
 check(await page.locator('#mrRouteView [data-sort-order]').inputValue()==="등급순","Detail back restores sort");
 await nav(page,"instagram");
 check(await page.locator('#mrRouteView .mr-instagram-gallery .mr-ig-tile').count()===5,"Domestic gallery five reels");
 await checkReelAlignment(page,"Domestic");
 await page.waitForFunction(()=>{const imgs=[...document.querySelectorAll("#mrRouteView .mr-ig-tile img")];return imgs.length===5&&imgs.every(x=>x.complete&&x.naturalWidth>0)},null,{timeout:18000});
 check(true,"All five visible domestic source poster files actually load");
 check(await page.locator('#mrRouteView .mr-instagram-gallery .mr-ig-tile [data-prod]').count()===5,"Every reel has production control");
 check(await page.locator('#mrRouteView .mr-instagram-gallery .mr-ig-tile [data-fav]').count()===5,"Every reel has favorite control");
 await click(page,'#mrRouteView .mr-ig-tile .mr-ig-cover');
 await page.locator('.mr-ig-preview-overlay .mr-ig-preview-panel iframe').waitFor();
 check((await page.locator('.mr-ig-preview-panel iframe').getAttribute("src")).includes("/embed/captioned/"),"Clicking reel cover opens official Instagram embed");
 await click(page,'.mr-ig-preview-panel [data-preview-close]');
 check(await page.locator('.mr-ig-preview-overlay').count()===0,"Official preview closes cleanly");
 await page.locator('#mrIgSearch').fill("razer");
 await page.locator('#mrIgSearch').press("Enter");
 check(await page.locator('#mrRouteView .mr-ig-tile').count()>=1,"Instagram caption and account search");
 await click(page,'#mrRouteView [data-ig-search-clear]');
 check(await page.locator('#mrRouteView .mr-ig-tile').count()===5,"Instagram search reset");
 await page.locator('#mrRouteView [data-sort-order]').selectOption("조회순");
 check(await page.locator('#mrRouteView [data-sort-order]').inputValue()==="조회순","Instagram views sort");
 await click(page,'#mrRouteView .mr-ig-tile [data-ig-detail]');
 await page.locator('#mrRouteView .mr-ig-detail').waitFor();
 const src=await page.locator('#mrRouteView .mr-ig-embed iframe').getAttribute("src");
 check(!!src&&src.includes("instagram.com/"),"Detail uses official original post embed");
 check(await page.locator('#mrRouteView .mr-ig-detail-links a').count()===2,"Detail offers reel and account links");
 const reelBefore=await page.locator('#mrRouteView .mr-ig-detail-info h1').innerText();
 check(await page.locator('#mrRouteView .mr-ig-detail-commands [data-command]').count()===5,"Instagram detail exposes all five commands");
 await click(page,'#mrRouteView .mr-ig-detail-commands [data-command="3"]');
 await page.locator('#mrCommandView [data-return-product]').waitFor();
 check((await page.locator('#mrCommandView .mr-generated').innerText()).includes(reelBefore),"Reel detail command uses exact original reel product");
 await page.evaluate(()=>history.back());
 await page.locator('#mrRouteView .mr-ig-detail').waitFor();
 check((await page.locator('#mrRouteView .mr-ig-detail-info h1').innerText())===reelBefore,"Browser back restores Instagram detail rather than skipping to reel list");
 await click(page,'#mrRouteView .mr-ig-detail-commands [data-command="3"]');
 await click(page,'#mrCommandView [data-return-product]');
 await page.locator('#mrRouteView .mr-ig-detail').waitFor();
 check((await page.locator('#mrRouteView .mr-ig-detail-info h1').innerText())===reelBefore,"Return from reel command restores same Instagram detail");

 await click(page,'#mrRouteView .mr-ig-save-actions [data-fav]');
 check((await page.locator('#mrRouteView .mr-ig-save-actions [data-fav]').innerText()).includes("해제"),"Reel saved from detail");
 await click(page,'#mrRouteView .mr-ig-save-actions [data-prod]');
 check((await page.locator('#mrRouteView .mr-ig-save-actions [data-prod]').innerText()).includes("해제"),"Reel queued from detail");
 await page.screenshot({path:"qa-v34-ig-detail.png",fullPage:true});
 await click(page,'#mrRouteView [data-detail-back]');
 check(await page.locator('#mrRouteView [data-sort-order]').inputValue()==="조회순","Reel detail back restores sort");
 await nav(page,"favorites");
 check(await page.locator('#mrRouteView .mr-ig-tile').count()===1,"Saved reel appears in favorites");
 await nav(page,"production");
 check(await page.locator('#mrRouteView .v33-production-row').count()===1,"Saved reel appears in production");
 const overlap=await page.locator('#mrRouteView .v33-row-product').first().evaluate(row=>{const photo=row.querySelector('img').getBoundingClientRect(),title=row.querySelector('span').getBoundingClientRect();return photo.right>title.left+1});
 check(!overlap,"Production thumbnail and title do not overlap");
 await page.locator('#mrRouteView [data-state]').first().selectOption("촬영중");
 check(await page.locator('#mrRouteView [data-state]').first().inputValue()==="촬영중","Production stage selector works");
 await page.screenshot({path:"qa-v34-ig-production.png",fullPage:true});
 await click(page,'#mrRouteView .v33-production-row [data-production-remove]');
 check(await page.locator('#mrRouteView .v33-production-row').count()===0,"Production delete removes test reel");
 await nav(page,"favorites");
 await click(page,'#mrRouteView .mr-ig-tile [data-fav]');
 check(await page.locator('#mrRouteView .mr-ig-tile').count()===0,"Favorite removal cleans test reel");
 await nav(page,"instagram");
 await click(page,'#mrRouteView [data-filter="해외상품"]');
 check(await page.locator('#mrRouteView .mr-ig-tile').count()===5,"Overseas first page has five");
 await page.waitForFunction(()=>{const imgs=[...document.querySelectorAll("#mrRouteView .mr-ig-tile img")];return imgs.length===5&&imgs.every(x=>x.complete&&x.naturalWidth>0)},null,{timeout:18000});
 check(true,"All five visible overseas original posters actually load");
 check(await page.locator('#mrRouteView .mr-pager button').count()===4,"Overseas gallery has four pages");
 await page.locator('#mrRouteView [data-sort-order]').selectOption("좋아요순");
 check(await page.locator('#mrRouteView [data-sort-order]').inputValue()==="좋아요순","Instagram likes sort");
 await click(page,'#mrRouteView .mr-pager [data-page="4"]');
 check(await page.locator('#mrRouteView .mr-ig-tile').count()===5,"Overseas fourth page five reels");
 await checkReelAlignment(page,"Overseas fourth page");
 await page.screenshot({path:"qa-v34-instagram-grid.png",fullPage:true});
 await click(page,'#mrCommandButton');
 await page.locator("#mrCommandInput").waitFor();
 const recentCount=a=>{const now=Date.now(),days=14*86400000;return a.filter(p=>{const t=Date.parse(p.timestamp||"");return Number.isFinite(t)&&t<=now&&now-t<=days}).length};
 let paidRequests=0;page.on("request",req=>{if(/(?:apify\.com|\.n8n\.cloud)/i.test(new URL(req.url()).hostname))paidRequests++});
 await page.locator("#mrCommandInput").fill("1-1번");
 await click(page,'#mrCommandForm button');
 await page.locator('#mrCommandResults .mr-chat-empty').waitFor();
 check((await page.locator('#mrCommandResults .mr-chat-empty').innerText()).includes("아직 등록된 조사 보고서가 없습니다"),"Empty chat research report never invents new products");
 check(await page.locator('#mrCommandResults [data-live-start],#mrCommandResults [data-live-key],#mrCommandResults [data-live-connect]').count()===0,"No paid n8n/Apify execution or credential forms remain");
 check(await page.locator('#mrCommandResults .mr-ig-tile').count()===0,"Previously saved reels are never passed off as new chat research");
 await click(page,'#mrCommandView [data-saved-search-command="1-1"]');
 check(await page.locator('#mrCommandResults .mr-ig-tile').count()===Math.min(5,recentCount(source.domestic)),"Prior domestic collection remains separately accessible");
 await click(page,'#mrCommandView [data-saved-search-command="1-2"]');
 check(await page.locator('#mrCommandResults .mr-ig-tile').count()===Math.min(5,recentCount(source.overseas)),"Prior overseas collection remains separately accessible");
 await click(page,'#mrCommandResults [data-report-group="all"][data-report-page="2"]');
 check(await page.locator('#mrCommandResults .mr-ig-tile').count()===5,"Legacy report shows five items per page");
 await page.evaluate(()=>history.back());
 await page.waitForFunction(()=>history.state?.mpView?.commandReportCode==="1-2"&&history.state?.mpView?.commandReportPages?.all!==2);
 check((await page.locator('#mrCommandResults [data-report-page="1"]').getAttribute("class")).includes("active"),"Browser back restores separate existing-data report");
 await click(page,'#mrCommandView [data-saved-search-command="1-3"]');
 check((await page.locator('#mrCommandResults .mr-report-rule').innerText()).includes("상품 등록일은 인기도 관측일로 사용하지 않습니다"),"Legacy Coupang report keeps evidence disclaimer");
 const qaItems=Array.from({length:7},(_,i)=>({
   productName:i===0?"QA 확인 판매 상품":i===1?"<script>fake injection</script>":"QA 상품 "+i,
   model:"TEST-01",category:"전자제품",sourcePlatform:"Instagram",reelUrl:"https://www.instagram.com/reel/TEST"+i+"/",accountUrl:"https://www.instagram.com/testaccount/",
   caption:"테스트 릴스 내용",publishedAt:"2026-09-27T00:00:00Z",metricsObservedAt:"2026-09-28T00:00:00Z",
   metrics:i===0?{views:13500,likes:101,comments:12,shares:null}:{views:null,likes:null,comments:null},
   sale:i===0?{status:"verified-on-sale",url:"https://www.coupang.com/vp/products/123",checkedAt:"2026-09-28T01:00:00Z",platform:"쿠팡"}:{status:"unknown"},
   recommendation:"모찌픽 QA 테스트",cautions:"실물 모델 미확인",sources:[{label:"원본",url:"https://www.instagram.com/reel/TEST"+i+"/"}]
 }));
 const qaReport={schema:"mozzipick.chat-reports.v1",updatedAt:"2026-09-28T02:00:00Z",reports:{
   "1":[],"1-1":[{id:"qa-new",command:"1-1",title:"QA 새 조사",createdAt:"2026-09-28T02:00:00Z",summary:"테스트 전용 자료",period:"14일",items:qaItems,notes:"실제 상품 아님"},
    {id:"qa-old",command:"1-1",title:"QA 과거 조사",createdAt:"2026-09-27T02:00:00Z",items:[]}],"1-2":[],"1-3":[]}};
 await page.route("**/data/command-reports.json*",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(qaReport)}));
 await page.locator("#mrCommandInput").fill("1-1");
 await click(page,'#mrCommandForm button');
 await page.locator('#mrCommandResults .mr-chat-item').first().waitFor();
 check(await page.locator('#mrCommandResults .mr-chat-item').count()===5,"Chat research report shows first five candidates");
 const contrast=await page.locator('#mrCommandResults .mr-chat-report').evaluate(el=>{
  const style=s=>getComputedStyle(el.querySelector(s));
  const rgb=c=>{const m=String(c).match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);return m?[+m[1],+m[2],+m[3]]:null};
  const l=c=>{const x=c.map(v=>{const n=v/255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4});return .2126*x[0]+.7152*x[1]+.0722*x[2]};
  const ratio=(fg,bg)=>{const x=l(rgb(fg)),y=l(rgb(bg));return Math.round(((Math.max(x,y)+.05)/(Math.min(x,y)+.05))*100)/100};
  const card=getComputedStyle(el),title=style('.mr-chat-item h3'),item=style('.mr-chat-item'),note=style('header p'),badge=style('.mr-chat-review-badge.unconfirmed'),selected=style('.mr-chat-review-filters [aria-pressed="true"]');
  return {reportBg:card.backgroundColor,title:ratio(title.color,item.backgroundColor),header:ratio(note.color,card.backgroundColor),unconfirmed:ratio(badge.color,badge.backgroundColor),selected:ratio(selected.color,selected.backgroundColor)};
 });
 check(contrast.reportBg==="rgb(255, 255, 255)","Research report uses explicit white canvas instead of dark fallback");
 check(contrast.title>=7&&contrast.header>=7,"Report titles and explanation pass enhanced 7:1 contrast");
 check(contrast.unconfirmed>=4.5&&contrast.selected>=4.5,"Review status and selected filter meet minimum 4.5:1 contrast");
 await page.locator("#mrCommandResults .mr-chat-report").screenshot({path:"qa-v34-report-r33-desktop.png"});
 check((await page.locator('#mrCommandResults .mr-chat-item').first().innerText()).includes("판매 중 · 판매처 확인"),"Verified sale status is evidence-based");
 check((await page.locator('#mrCommandResults .mr-chat-item').first().innerText()).includes("13,500"),"Verified view count rendered with locale formatting");
 check((await page.locator('#mrCommandResults .mr-chat-item').nth(1).innerText()).includes("미확인"),"Missing engagement is labeled unverified");
 check(await page.locator('#mrCommandResults .mr-chat-item script').count()===0,"Scraped user content is HTML escaped");
 check(await page.locator('#mrCommandResults .mr-chat-archives option').count()===2,"Past chat research reports remain accessible in archive");
 check(await page.locator('#mrCommandResults .mr-chat-review-badge.unconfirmed').count()===5,"Research items begin with personal unchecked status");
 check((await page.locator('#mrCommandResults .mr-chat-review-summary').innerText()).includes("미확인 7개"),"Unreviewed total counts all seven, not just page one");
 await click(page,'#mrCommandResults .mr-chat-item:first-child [data-chat-review-index]');
 check(await page.locator('#mrCommandResults .mr-chat-item:first-child .mr-chat-review-badge.confirmed').count()===1,"Confirmation visibly changes personal badge");
 check((await page.locator('#mrCommandResults .mr-chat-review-summary').innerText()).includes("확인 1개"),"Confirmation updates overall reviewed count");
 check((await page.locator('#mrCommandResults .mr-chat-item:first-child').innerText()).includes("판매 중 · 판매처 확인"),"Review status does not alter independent sale claims");
 check(await page.evaluate(()=>Boolean(JSON.parse(localStorage.getItem("mozzipick.chat-review.v1")||"{}")["url:https://www.instagram.com/reel/TEST0"]?.checkedAt)),"Confirmation persists by stable reel URL and time in localStorage");
 await click(page,'#mrCommandResults [data-chat-review-filter="confirmed"]');
 check(await page.locator('#mrCommandResults .mr-chat-item').count()===1,"Confirmed-only filter shows reviewed candidates");
 await click(page,'#mrCommandResults [data-chat-review-filter="unconfirmed"]');
 check(await page.locator('#mrCommandResults .mr-chat-item').count()===5,"Unconfirmed-only filter paginates remaining six candidates");
 check(await page.locator('#mrCommandResults [data-chat-page="2"]').count()===1,"Unconfirmed filter has page two");
 await page.evaluate(()=>history.back());
 await page.waitForFunction(()=>history.state?.mpView?.commandResearch?.reviewFilter==="confirmed");
 check(await page.locator('#mrCommandResults .mr-chat-item').count()===1,"Back restores prior review filter");
 await click(page,'#mrCommandResults [data-chat-review-filter="all"]');
 await click(page,'#mrCommandResults [data-chat-reload]');
 await page.locator('#mrCommandResults .mr-chat-item:first-child .mr-chat-review-badge.confirmed').waitFor();
 check(true,"Confirmed status persists across report refetch");
 await click(page,'#mrCommandResults [data-chat-page="2"]');
 check(await page.locator('#mrCommandResults .mr-chat-item').count()===2,"Second page contains remaining two research candidates");
 await page.evaluate(()=>history.back());
 await page.waitForFunction(()=>history.state?.mpView?.commandResearch?.page===1);
 await page.locator('#mrCommandResults .mr-chat-item').first().waitFor();
 check(await page.locator('#mrCommandResults .mr-chat-item').count()===5,"Browser back returns to report page one");
 check(await page.locator('#mrCommandResults .mr-chat-item:first-child .mr-chat-review-badge.confirmed').count()===1,"Back preserves personal confirmation");
 await click(page,'#mrCommandResults .mr-chat-item:first-child [data-chat-review-index]');
 check(await page.locator('#mrCommandResults .mr-chat-item:first-child .mr-chat-review-badge.unconfirmed').count()===1,"Second click revokes confirmation");
 check((await page.locator('#mrCommandResults .mr-chat-review-summary').innerText()).includes("미확인 7개"),"Revocation updates summary totals");
 await page.locator("#mrCommandInput").fill("1-2");
 await click(page,'#mrCommandForm button');
 await page.locator('#mrCommandResults .mr-chat-empty').waitFor();
 check((await page.locator('#mrCommandResults .mr-chat-empty').innerText()).includes("아직 등록된"),"Overseas command has its own honest empty report");
 await page.locator("#mrCommandInput").fill("1-3번");
 await click(page,'#mrCommandForm button');
 await page.locator('#mrCommandResults .mr-chat-empty').waitFor();
 check((await page.locator('#mrCommandResults .mr-chat-report header').innerText()).includes("쿠팡"),"Coupang command maps to its separate report");
 await page.locator("#mrCommandInput").fill("1번");
 await click(page,'#mrCommandForm button');
 await page.locator('#mrCommandResults .mr-chat-empty').waitFor();
 check((await page.locator('#mrCommandResults .mr-chat-report header').innerText()).includes("통합"),"Integrated command maps to its separate report");
 check(paidRequests===0,"All command 1 viewer interactions issue zero Apify or n8n requests");
 await click(page,'#mrCommandView .mr-command-grid [data-command="2"]');
 await page.locator('#mrCommandView .mr-command-detail').waitFor();
 await click(page,'#mrCommandView [data-change-product]');
 check(await page.locator('#mrCommandView [data-product-recent],#mrCommandView .mr-command-recent').count()===0,"Recent viewed products block removed");
 check(await page.locator('#mrCommandView [data-product-search]').isVisible(),"Product search remains available");
 await page.locator('#mrCommandView [data-product-search]').fill("현미경");
 check(await page.locator('#mrCommandView [data-pick-product]').count()>0,"Product picker search still returns results");
 await click(page,'#mrCommandView [data-pick-product]');
 check((await page.locator('#mrCommandView .mr-command-selected strong').innerText()).includes("현미경"),"Product selection still updates command target");
 await page.locator('#mrCommandView input[name="mr-script-format"][value="리뷰형"]').check();
 check((await page.locator('#mrCommandView .mr-generated').innerText()).includes("선택 형식: 리뷰형"),"Script format controls update output");
 await click(page,'#mrCommandView [data-copy-command]');
 await page.locator('#mrCommandView [data-copy-command][data-copy-status="success"]').waitFor({timeout:6000});
 check(true,"Command generated text is copyable");

 const mobile=await browser.newPage({viewport:{width:375,height:812},isMobile:true});
 await mobile.goto(base+"#mp=route%3Ainstagram",{waitUntil:"domcontentloaded"});
 await mobile.locator('#mrRouteView .mr-ig-tile').first().waitFor();
 check(await mobile.locator('#mrRouteView .mr-ig-tile').count()===5,"Mobile Instagram loads 5 reels");
 await checkReelAlignment(mobile,"Mobile domestic");
 const dims=await mobile.locator('#mrRouteView .mr-instagram-gallery').evaluate(el=>({width:el.getBoundingClientRect().width,display:getComputedStyle(el).display,template:getComputedStyle(el).gridTemplateColumns,columns:[...el.children].slice(0,2).map(x=>({width:x.getBoundingClientRect().width,display:getComputedStyle(x).display,column:getComputedStyle(x).gridColumn,gridArea:getComputedStyle(x).gridArea,cssWidth:getComputedStyle(x).width})),children:[...el.children].slice(0,2).map(x=>x.getBoundingClientRect().width)}));
 console.log("MOBILE GALLERY DIMENSIONS",JSON.stringify({dims,viewport:await mobile.evaluate(()=>({innerWidth,clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,media760:matchMedia("(max-width:760px)").matches}))}));await mobile.screenshot({path:"qa-v34-mobile-gallery.png",fullPage:true});
 check(dims.children.length===2&&dims.children[0]<dims.width*.7,"Mobile gallery uses two columns");
 await click(mobile,'#mrRouteView .mr-ig-tile [data-ig-detail]');
 check(await mobile.locator('#mrRouteView .mr-ig-detail').isVisible(),"Mobile reel detail opens");
 await click(mobile,'#mrRouteView .mr-ig-detail-commands [data-command="2"]');
 await mobile.locator('#mrCommandView [data-return-product]').waitFor();
 await mobile.evaluate(()=>history.back());
 await mobile.locator('#mrRouteView .mr-ig-detail').waitFor();
 check(await mobile.evaluate(()=>/^detail:/.test(history.state?.mozzipick||"")),"Mobile device back returns to original reel detail");
 await mobile.evaluate(()=>history.back());
 await mobile.locator('#mrRouteView .mr-instagram-gallery').waitFor();
 check(await mobile.evaluate(()=>history.state?.mozzipick==="route:instagram"),"Mobile device back returns to original Instagram list");
 await mobile.route("**/data/command-reports.json*",route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(qaReport)}));
 await mobile.goto(base+"&qaMobileChatReport=1#mp=command%3Acenter",{waitUntil:"domcontentloaded"});
 await mobile.locator("#mrCommandInput").waitFor();
 await mobile.locator("#mrCommandInput").fill("1-1");
 await click(mobile,"#mrCommandForm button");
 await mobile.locator("#mrCommandResults .mr-chat-item").first().waitFor();
 check(await mobile.locator("#mrCommandResults .mr-chat-item").count()===5,"Mobile chat research report displays five candidates");
 await mobile.locator("#mrCommandResults .mr-chat-report").screenshot({path:"qa-v34-report-r33-mobile.png"});
 const reportFits=await mobile.locator("#mrCommandResults .mr-chat-report").evaluate(el=>el.getBoundingClientRect().right<=window.innerWidth+2&&el.getBoundingClientRect().left>=-2);
 check(reportFits,"Mobile chat report fits the 375px screen without horizontal clipping");
 await click(mobile,'#mrCommandResults .mr-chat-item:first-child [data-chat-review-index]');
 check(await mobile.locator('#mrCommandResults .mr-chat-review-badge.confirmed').count()===1,"Mobile checkbox activates");
 await click(mobile,'#mrCommandResults [data-chat-review-filter="confirmed"]');
 check(await mobile.locator("#mrCommandResults .mr-chat-item").count()===1,"Mobile confirmed-only filter");
 await click(mobile,'#mrCommandResults [data-chat-review-filter="all"]');
 await click(mobile,'#mrCommandResults [data-chat-page="2"]');
 check(await mobile.locator("#mrCommandResults .mr-chat-item").count()===2,"Mobile chat report pagination retains remaining candidates");

 // r27 full-navigation regression: every back/forward must restore the preceding
 // real UI state, never a synthetic homepage entry or a reset filter/page.
 const h=await context.newPage();
 h.on("pageerror",e=>errors.push("navigation QA: "+e.message));
 await h.goto(base,{waitUntil:"domcontentloaded"});
 await h.locator("#mrHomeDashboard .mr-card").first().waitFor();
 check(await h.evaluate(()=>history.state?.mozzipick==="home"&&history.state?.mpIndex===0),"Initial screen has one real history entry, no artificial homepage");
 await nav(h,"categories");
 check(await h.evaluate(()=>history.state?.mozzipick==="route:categories"),"Main to category menu creates route history");
 await h.locator('#mrRouteView [data-sort-order]').selectOption("최신순");
 check(await h.locator('#mrRouteView [data-sort-order]').inputValue()==="최신순","Category sorting records selected order");
 await click(h,'#mrRouteView [data-filter="S급"]');
 check(await h.locator('#mrRouteView [data-filter="S급"]').getAttribute("class").then(v=>v.includes("active")),"Category filtering records selected filter");
 await h.evaluate(()=>history.back());
 await h.waitForFunction(()=>history.state?.mpIndex===2);
 check(await h.locator('#mrRouteView [data-sort-order]').inputValue()==="최신순"&&await h.locator('#mrRouteView [data-filter="전체"]').getAttribute("class").then(v=>v.includes("active")),"Back restores preceding category filter and sort, not homepage");
 await h.evaluate(()=>history.back());
 await h.waitForFunction(()=>history.state?.mpIndex===1);
 check(await h.locator('#mrRouteView [data-sort-order]').inputValue()==="등급순","Second back restores preceding sort state");
 await h.evaluate(()=>history.back());
 await h.waitForFunction(()=>history.state?.mpIndex===0);
 check(await h.locator('#mrHomeDashboard .mr-card').first().isVisible(),"Third back reaches original homepage exactly once");
 await h.evaluate(()=>history.forward());await h.waitForFunction(()=>history.state?.mpIndex===1);
 check(await h.locator('#mrRouteView [data-sort-order]').inputValue()==="등급순","Browser forward restores menu state");
 await nav(h,"instagram");
 await click(h,'#mrRouteView [data-filter="해외상품"]');
 await h.locator('#mrRouteView [data-sort-order]').selectOption("좋아요순");
 await click(h,'#mrRouteView .mr-pager [data-page="4"]');
 check(await h.locator('#mrRouteView .mr-ig-tile').count()===5,"Instagram page four is visible before menu switch");
 await nav(h,"time");
 await h.evaluate(()=>history.back());
 await h.waitForFunction(()=>history.state?.mozzipick==="route:instagram");
 check(await h.locator('#mrRouteView [data-filter="해외상품"]').getAttribute("class").then(v=>v.includes("active"))&&await h.locator('#mrRouteView [data-sort-order]').inputValue()==="좋아요순"&&await h.locator('#mrRouteView .mr-pager [data-page="4"]').getAttribute("class").then(v=>v.includes("active")),"Back across menus restores Instagram region, sort, and page four");
 await h.evaluate(()=>history.back());
 await h.waitForFunction(()=>history.state?.mpView?.page===1);
 check(await h.locator('#mrRouteView [data-filter="해외상품"]').getAttribute("class").then(v=>v.includes("active")),"Back from page four returns to preceding page of same menu");
 await click(h,'#mrRouteView .mr-ig-tile [data-ig-detail]');
 const savedReel=await h.locator('#mrRouteView .mr-ig-detail-info h1').innerText();
 await nav(h,"categories");
 await h.evaluate(()=>history.back());
 await h.locator('#mrRouteView .mr-ig-detail-info h1').waitFor();
 check((await h.locator('#mrRouteView .mr-ig-detail-info h1').innerText())===savedReel,"Back from another menu returns to preceding detail rather than homepage");
 await h.evaluate(()=>history.back());
 await h.locator('#mrRouteView .mr-instagram-gallery').waitFor();
 check(await h.locator('#mrRouteView [data-filter="해외상품"]').getAttribute("class").then(v=>v.includes("active")),"Back from detail restores the exact preceding reel list");
 await click(h,'#mrRouteView .mr-ig-tile .mr-ig-cover');
 await h.locator(".mr-ig-preview-overlay").waitFor();
 check(await h.evaluate(()=>history.state?.mozzipick.startsWith("preview:")),"Reel preview creates its own history entry");
 await h.evaluate(()=>history.back());
 await h.waitForFunction(()=>!document.querySelector(".mr-ig-preview-overlay"));
 check(await h.locator('#mrRouteView .mr-instagram-gallery').isVisible(),"Back closes preview without leaving its menu");
 await h.evaluate(()=>history.forward());
 await h.locator(".mr-ig-preview-overlay").waitFor();
 check(await h.locator(".mr-ig-preview-overlay").isVisible(),"Forward reopens the previous preview");
 await click(h,'.mr-ig-preview-overlay [data-preview-close]');
 await h.waitForFunction(()=>!document.querySelector(".mr-ig-preview-overlay"));
 check(await h.locator('#mrRouteView .mr-instagram-gallery').isVisible(),"Preview X closes via same history behavior");
 await click(h,"#mrCommandButton");
 await h.locator("#mrCommandView .mr-command-grid").waitFor();
 await click(h,'#mrCommandView .mr-command-grid [data-command="2"]');
 await click(h,'#mrCommandView .mr-command-quick [data-command="3"]');
 await h.evaluate(()=>history.back());
 await h.waitForFunction(()=>history.state?.mozzipick==="command:2");
 check(await h.locator('#mrCommandView .mr-command-detail header h1').innerText().then(v=>v.includes("영상 대본")),"Back from command 3 restores command 2, not homepage");
 await h.evaluate(()=>history.back());
 await h.waitForFunction(()=>history.state?.mozzipick==="command:center");
 check(await h.locator('#mrCommandInput').isVisible(),"Back from command 2 restores command center");
 await h.locator("#mrCommandInput").fill("1-1");
 await click(h,'#mrCommandView [data-saved-search-command="1-1"]');
 await h.locator('#mrCommandResults .mr-ig-tile').first().waitFor();
 await click(h,'#mrCommandResults .mr-ig-tile [data-ig-detail]');
 await h.locator('#mrRouteView .mr-ig-detail').waitFor();
 await h.evaluate(()=>history.back());
 await h.locator('#mrCommandResults .mr-ig-tile').first().waitFor();
 check(await h.locator('#mrCommandInput').inputValue()==="1-1"&&await h.locator('#mrCommandResults .mr-search-report').isVisible(),"Back from saved-search detail restores the exact separate cached report");
 // Every top navigation route must return to the exact previous menu, including empty saved lists.
 for(const v of ["time","viral","favorites","production","quality","instagram"]){
  await nav(h,v);
  const savedSort=await h.locator('#mrRouteView [data-sort-order]').inputValue();
  await nav(h,"categories");
  await h.evaluate(()=>history.back());
  await h.waitForFunction(expected=>history.state?.mozzipick==="route:"+expected,v);
  check(await h.locator('#mrRouteView').getAttribute("data-route")===v&&await h.locator('#mrRouteView [data-sort-order]').inputValue()===savedSort,"Global previous-screen return retains "+v+" menu and sorting");
 }
 // r32: only personally checked 1-1 research is visible in domestic Instagram, with reversible status.
 const approvalContext=await browser.newContext({viewport:{width:1280,height:900}});
 const approvalPage=await approvalContext.newPage();
 approvalPage.on("pageerror",e=>errors.push("Approved import: "+e.message));
 let approvalPaidRequests=0;
 approvalPage.on("request",req=>{if(/(?:apify\.com|\.n8n\.cloud)/i.test(new URL(req.url()).hostname))approvalPaidRequests++});
 await approvalPage.route("**/data/command-reports.json*",r=>r.fulfill({status:200,contentType:"application/json",body:JSON.stringify(qaReport)}));
 await approvalPage.goto(base+"&approvedQA=1",{waitUntil:"domcontentloaded"});
 await approvalPage.locator("#mrHomeDashboard .mr-card").first().waitFor();
 await nav(approvalPage,"instagram");
 check(await approvalPage.locator("#mrRouteView .mr-ig-tile").count()===5,"Unreviewed research adds zero candidates to domestic Instagram");
 await approvalPage.locator("#mrIgSearch").fill("QA 확인 판매 상품");
 await click(approvalPage,"#mrRouteView [data-ig-search-run]");
 check(await approvalPage.locator("#mrRouteView .mr-ig-tile").count()===0,"Unreviewed research not shown in Instagram search");
 await click(approvalPage,"#mrCommandButton");
 await approvalPage.locator("#mrCommandInput").fill("1-1");
 await click(approvalPage,"#mrCommandForm button");
 await approvalPage.locator("#mrCommandResults .mr-chat-item").first().waitFor();
 await click(approvalPage,"#mrCommandResults .mr-chat-item:first-child [data-chat-review-index]");
 check(await approvalPage.locator("#mrCommandResults .mr-chat-review-badge.confirmed").count()===1,"Only one manually checked domestic candidate");
 await nav(approvalPage,"instagram");
 await approvalPage.locator("#mrIgSearch").fill("QA 확인 판매 상품");
 await click(approvalPage,"#mrRouteView [data-ig-search-run]");
 check(await approvalPage.locator("#mrRouteView .mr-ig-tile").count()===1,"Checked candidate moves to domestic Instagram");
 check((await approvalPage.locator("#mrRouteView .mr-ig-chat-approved").innerText()).includes("1-1 보고서"),"Moved item distinctly marked personal approval");
 check((await approvalPage.locator("#mrRouteView .mr-ig-under").innerText()).includes("좋아요 101"),"Moved item keeps reported metrics");
 await click(approvalPage,'#mrRouteView .mr-ig-tile [data-ig-detail]');
 await approvalPage.locator("#mrRouteView .mr-ig-detail").waitFor();
 check((await approvalPage.locator("#mrRouteView .mr-ig-detail-info h1").innerText())==="QA 확인 판매 상품","Moved item has exact original detail");
 check((await approvalPage.locator("#mrRouteView .mr-ig-detail .mr-ig-source").innerText()).includes("같은 브라우저"),"Detail discloses local browser-only status");
 await click(approvalPage,"#mrCommandButton");
 await approvalPage.locator("#mrCommandInput").fill("1-1");
 await click(approvalPage,"#mrCommandForm button");
 await approvalPage.locator("#mrCommandResults .mr-chat-item").first().waitFor();
 await click(approvalPage,"#mrCommandResults .mr-chat-item:first-child [data-chat-review-index]");
 check(await approvalPage.locator("#mrCommandResults .mr-chat-review-badge.unconfirmed").count()===5,"Second click revokes approval without erasing report");
 await nav(approvalPage,"instagram");
 await approvalPage.locator("#mrIgSearch").fill("QA 확인 판매 상품");
 await click(approvalPage,"#mrRouteView [data-ig-search-run]");
 check(await approvalPage.locator("#mrRouteView .mr-ig-tile").count()===0,"Revoked candidate automatically removed from approved import");
 await approvalPage.locator("#mrIgSearch").fill("");
 await click(approvalPage,"#mrRouteView [data-ig-search-run]");
 check(await approvalPage.locator("#mrRouteView .mr-ig-tile").count()===5,"Original domestic reels remain untouched");
 check(approvalPaidRequests===0,"Import and rollback call neither n8n nor Apify");
 await approvalContext.close();
 await h.close();
 check(errors.length===0,"No uncaught browser runtime errors across desktop and mobile");

 await page.close();await mobile.close();
}
try{await run();}catch(e){errors.push(e.stack||String(e));process.exitCode=1;}finally{
 console.log(JSON.stringify({findings,errors},null,2));
 await browser.close();
}
