import { chromium } from "playwright";
import fs from "node:fs";
const base = "http://127.0.0.1:8765/?v=v34-ig-completion";
const browser = await chromium.launch({ headless: true });
const findings = [], errors = [];
function check(value, message){findings.push({pass:!!value,message}); if(!value)throw Error("FAIL: "+message)}
async function click(page, selector){await page.locator(selector).first().click({timeout:10000})}
async function nav(page, route){await click(page, '.mp-header-nav nav [data-view="'+route+'"]');await page.locator('#mrRouteView[data-route="'+route+'"]').waitFor()}
async function checkReelAlignment(page,label){
 const r=await page.locator('#mrRouteView .mr-instagram-gallery>.mr-ig-tile').evaluateAll(cards=>cards.map(card=>{
  const box=card.getBoundingClientRect();
  const actions=card.querySelector('.mr-ig-tile-actions');
  const name=card.querySelector('.mr-ig-under>b');
  return {top:box.top,bottom:box.bottom,actionsBottom:actions?.getBoundingClientRect().bottom,
   actionsTop:actions?.getBoundingClientRect().top,nameHeight:name?.getBoundingClientRect().height};
 }));
 const rows=[];
 for(const item of r){let group=rows.find(group=>Math.abs(group[0].top-item.top)<2);if(group)group.push(item);else rows.push([item]);}
 const within=(arr,key,eps)=>Math.max(...arr.map(x=>x[key]))-Math.min(...arr.map(x=>x[key]))<=eps;
 const align=rows.every(row=>within(row,'bottom',2)&&within(row,'actionsTop',2)&&within(row,'actionsBottom',2)&&within(row,'nameHeight',2));
 check(r.length===5&&align,label+" per-row card bottoms, names and button baselines align");
}
async function run(){
 const source=JSON.parse(fs.readFileSync("data/instagram-electronics.json","utf8"));
 const context=await browser.newContext({viewport:{width:1440,height:900},permissions:["clipboard-read","clipboard-write"]});
 const page=await context.newPage();
 page.on("pageerror", e => errors.push(e.message));
 await page.goto(base, {waitUntil:"domcontentloaded"});
 await page.locator("#mrHomeDashboard .mr-card").first().waitFor({timeout:20000});
 check(await page.locator("#mrHomeDashboard .mr-card").count()>=4,"Homepage product cards load");
 const css=await page.locator('link[href*="v33.css"]').last().getAttribute("href");
 check(css?.includes("v35-detail-command-r23"),"V3.5 product-detail command stylesheet linked");
 await nav(page,"categories");
 check(await page.locator('#mrRouteView [data-sort-order] option').count()===3,"Category sort options");
 await page.locator('#mrRouteView [data-sort-order]').selectOption("등급순");
 check(await page.locator('#mrRouteView .mr-card').count()===5,"Category five-item pagination");
 const clipped=await page.locator('#mrRouteView .mr-card').evaluateAll(cards=>cards.some(card=>{const a=card.querySelector('.mr-card-actions');return a&&a.getBoundingClientRect().bottom>card.getBoundingClientRect().bottom+2}));
 check(!clipped,"Category action buttons not clipped");
 await click(page,'#mrRouteView .mr-card [data-detail]');
 await page.locator('#mrRouteView .mr-detail-page').waitFor();
 check(await page.locator('#mrRouteView [data-copyword]').count()===4,"Product detail four search keywords");
 const productBefore=await page.locator('#mrRouteView .mr-detail-summary h1').innerText();
 check(await page.evaluate(()=>/^detail:/.test(history.state?.mozzipick||"")),"Opening product detail adds dedicated browser history entry");
 await click(page,'#mrRouteView .mr-detail-quick [data-command="2"]');
 await page.locator('#mrCommandView .mr-command-return [data-return-product]').waitFor();
 check((await page.locator('#mrCommandView .mr-command-selected strong').innerText())===productBefore,"Detail command uses exact selected product");
 await page.evaluate(()=>history.back());
 await page.locator('#mrRouteView .mr-detail-page').waitFor();
 check(await page.evaluate(()=>/^detail:/.test(history.state?.mozzipick||"")),"Browser back from command restores detail history entry");
 check((await page.locator('#mrRouteView .mr-detail-summary h1').innerText())===productBefore,"Browser back restores exact original product detail");
 await page.evaluate(()=>history.forward());
 await page.locator('#mrCommandView [data-return-product]').waitFor();
 check((await page.locator('#mrCommandView .mr-command-selected strong').innerText())===productBefore,"Browser forward restores command bound to the same product");
 await click(page,'#mrCommandView [data-return-product]');
 await page.locator('#mrRouteView .mr-detail-page').waitFor();
 await click(page,'#mrRouteView .mr-detail-quick [data-command="2"]');
 check((await page.locator('#mrCommandView .mr-generated').innerText()).includes("나도"),"Detail script includes complete comment CTA");
 await page.locator('#mrCommandView input[name="mr-script-format"][value="리뷰형"]').check();
 check((await page.locator('#mrCommandView .mr-generated').innerText()).includes("선택 형식: 리뷰형"),"Detail script option produces selected review draft");
 for(const n of [1,3,4,5]){
  await click(page,'#mrCommandView .mr-command-quick [data-command="'+n+'"]');
  check((await page.locator('#mrCommandView .mr-generated').innerText()).includes(productBefore),"Detail command "+n+" retains selected product");
 }
 check((await page.locator('#mrCommandView .mr-generated').innerText()).includes("링크 미확인")||await page.locator('#mrCommandView .mr-generated').innerText().then(x=>x.includes("coupang.com")),"Detail DM does not invent product link");
 await click(page,'#mrCommandView [data-return-product]');
 await page.locator('#mrRouteView .mr-detail-page').waitFor();
 check((await page.locator('#mrRouteView .mr-detail-summary h1').innerText())===productBefore,"Return from command restores original detail");
 check(await page.evaluate(()=>/^detail:/.test(history.state?.mozzipick||"")),"Command return lands on detail history entry");
 await page.evaluate(()=>history.back());
 await page.locator('#mrRouteView [data-sort-order]').waitFor();
 check(await page.evaluate(()=>history.state?.mozzipick==="route:categories"),"Browser back from detail restores original category URL state");
 check(await page.locator('#mrRouteView [data-sort-order]').inputValue()==="등급순","Browser back restores category sort");
 await page.evaluate(()=>history.forward());
 await page.locator('#mrRouteView .mr-detail-page').waitFor();
 check((await page.locator('#mrRouteView .mr-detail-summary h1').innerText())===productBefore,"Browser forward restores the original detail");
 await page.evaluate(()=>history.back());
 await page.locator('#mrRouteView [data-sort-order]').waitFor();
 await click(page,'#mrRouteView .mr-card [data-detail]');
 await click(page,'#mrRouteView [data-detail-back]');
 await page.locator('#mrRouteView [data-sort-order]').waitFor();
 check(await page.evaluate(()=>history.state?.mozzipick==="route:categories"),"On-page detail back restores original history entry");
 check(await page.locator('#mrRouteView [data-sort-order]').inputValue()==="등급순","Detail back restores sort");
 await nav(page,"instagram");
 check(await page.locator('#mrRouteView .mr-instagram-gallery .mr-ig-tile').count()===5,"Domestic gallery five reels");
 await checkReelAlignment(page,"Domestic");
 await page.waitForFunction(()=>{const imgs=[...document.querySelectorAll("#mrRouteView .mr-ig-tile img")];return imgs.length===5&&imgs.every(x=>x.complete&&x.naturalWidth>0)},null,{timeout:18000});
 check(true,"All five visible domestic source poster files actually load");
 check(await page.locator('#mrRouteView .mr-instagram-gallery .mr-ig-tile [data-prod]').count()===5,"Every reel has production control");
 check(await page.locator('#mrRouteView .mr-instagram-gallery .mr-ig-tile [data-fav]').count()===5,"Every reel has favorite control");
 await click(page,'#mrRouteView .mr-ig-tile .mr-ig-cover');
 await page.locator('.mr-ig-preview-overlay .mr-ig-preview-panel iframe').waitFor();
 check((await page.locator('.mr-ig-preview-panel iframe').getAttribute("src")).includes("/embed/captioned/"),"Clicking reel cover opens official Instagram embed");
 await click(page,'.mr-ig-preview-panel [data-preview-close]');
 check(await page.locator('.mr-ig-preview-overlay').count()===0,"Official preview closes cleanly");
 await page.locator('#mrIgSearch').fill("razer");
 await page.locator('#mrIgSearch').press("Enter");
 check(await page.locator('#mrRouteView .mr-ig-tile').count()>=1,"Instagram caption and account search");
 await click(page,'#mrRouteView [data-ig-search-clear]');
 check(await page.locator('#mrRouteView .mr-ig-tile').count()===5,"Instagram search reset");
 await page.locator('#mrRouteView [data-sort-order]').selectOption("조회순");
 check(await page.locator('#mrRouteView [data-sort-order]').inputValue()==="조회순","Instagram views sort");
 await click(page,'#mrRouteView .mr-ig-tile [data-ig-detail]');
 await page.locator('#mrRouteView .mr-ig-detail').waitFor();
 const src=await page.locator('#mrRouteView .mr-ig-embed iframe').getAttribute("src");
 check(!!src&&src.includes("instagram.com/"),"Detail uses official original post embed");
 check(await page.locator('#mrRouteView .mr-ig-detail-links a').count()===2,"Detail offers reel and account links");
 const reelBefore=await page.locator('#mrRouteView .mr-ig-detail-info h1').innerText();
 check(await page.locator('#mrRouteView .mr-ig-detail-commands [data-command]').count()===5,"Instagram detail exposes all five commands");
 await click(page,'#mrRouteView .mr-ig-detail-commands [data-command="3"]');
 await page.locator('#mrCommandView [data-return-product]').waitFor();
 check((await page.locator('#mrCommandView .mr-generated').innerText()).includes(reelBefore),"Reel detail command uses exact original reel product");
 await page.evaluate(()=>history.back());
 await page.locator('#mrRouteView .mr-ig-detail').waitFor();
 check((await page.locator('#mrRouteView .mr-ig-detail-info h1').innerText())===reelBefore,"Browser back restores Instagram detail rather than skipping to reel list");
 await click(page,'#mrRouteView .mr-ig-detail-commands [data-command="3"]');
 await click(page,'#mrCommandView [data-return-product]');
 await page.locator('#mrRouteView .mr-ig-detail').waitFor();
 check((await page.locator('#mrRouteView .mr-ig-detail-info h1').innerText())===reelBefore,"Return from reel command restores same Instagram detail");

 await click(page,'#mrRouteView .mr-ig-save-actions [data-fav]');
 check((await page.locator('#mrRouteView .mr-ig-save-actions [data-fav]').innerText()).includes("해제"),"Reel saved from detail");
 await click(page,'#mrRouteView .mr-ig-save-actions [data-prod]');
 check((await page.locator('#mrRouteView .mr-ig-save-actions [data-prod]').innerText()).includes("해제"),"Reel queued from detail");
 await page.screenshot({path:"qa-v34-ig-detail.png",fullPage:true});
 await click(page,'#mrRouteView [data-detail-back]');
 check(await page.locator('#mrRouteView [data-sort-order]').inputValue()==="조회순","Reel detail back restores sort");
 await nav(page,"favorites");
 check(await page.locator('#mrRouteView .mr-ig-tile').count()===1,"Saved reel appears in favorites");
 await nav(page,"production");
 check(await page.locator('#mrRouteView .v33-production-row').count()===1,"Saved reel appears in production");
 const overlap=await page.locator('#mrRouteView .v33-row-product').first().evaluate(row=>{const photo=row.querySelector('img').getBoundingClientRect(),title=row.querySelector('span').getBoundingClientRect();return photo.right>title.left+1});
 check(!overlap,"Production thumbnail and title do not overlap");
 await page.locator('#mrRouteView [data-state]').first().selectOption("촬영중");
 check(await page.locator('#mrRouteView [data-state]').first().inputValue()==="촬영중","Production stage selector works");
 await page.screenshot({path:"qa-v34-ig-production.png",fullPage:true});
 await click(page,'#mrRouteView .v33-production-row [data-production-remove]');
 check(await page.locator('#mrRouteView .v33-production-row').count()===0,"Production delete removes test reel");
 await nav(page,"favorites");
 await click(page,'#mrRouteView .mr-ig-tile [data-fav]');
 check(await page.locator('#mrRouteView .mr-ig-tile').count()===0,"Favorite removal cleans test reel");
 await nav(page,"instagram");
 await click(page,'#mrRouteView [data-filter="해외상품"]');
 check(await page.locator('#mrRouteView .mr-ig-tile').count()===5,"Overseas first page has five");
 await page.waitForFunction(()=>{const imgs=[...document.querySelectorAll("#mrRouteView .mr-ig-tile img")];return imgs.length===5&&imgs.every(x=>x.complete&&x.naturalWidth>0)},null,{timeout:18000});
 check(true,"All five visible overseas original posters actually load");
 check(await page.locator('#mrRouteView .mr-pager button').count()===4,"Overseas gallery has four pages");
 await page.locator('#mrRouteView [data-sort-order]').selectOption("좋아요순");
 check(await page.locator('#mrRouteView [data-sort-order]').inputValue()==="좋아요순","Instagram likes sort");
 await click(page,'#mrRouteView .mr-pager [data-page="4"]');
 check(await page.locator('#mrRouteView .mr-ig-tile').count()===5,"Overseas fourth page five reels");
 await checkReelAlignment(page,"Overseas fourth page");
 await page.screenshot({path:"qa-v34-instagram-grid.png",fullPage:true});
 await click(page,'#mrCommandButton');
 await page.locator("#mrCommandInput").waitFor();
 await page.locator("#mrCommandInput").fill("1-1");
 await click(page,'#mrCommandForm button');
 check(await page.locator('#mrCommandResults .mr-ig-tile').count()===source.domestic.length,"Domestic command output matches source");
 await page.locator("#mrCommandInput").fill("1-2");
 await click(page,'#mrCommandForm button');
 check(await page.locator('#mrCommandResults .mr-ig-tile').count()===source.overseas.length,"Overseas command output matches source");
 await click(page,'#mrCommandView .mr-command-grid [data-command="2"]');
 await page.locator('#mrCommandView .mr-command-detail').waitFor();
 await click(page,'#mrCommandView [data-change-product]');
 check(await page.locator('#mrCommandView [data-product-recent],#mrCommandView .mr-command-recent').count()===0,"Recent viewed products block removed");
 check(await page.locator('#mrCommandView [data-product-search]').isVisible(),"Product search remains available");
 await page.locator('#mrCommandView [data-product-search]').fill("현미경");
 check(await page.locator('#mrCommandView [data-pick-product]').count()>0,"Product picker search still returns results");
 await click(page,'#mrCommandView [data-pick-product]');
 check((await page.locator('#mrCommandView .mr-command-selected strong').innerText()).includes("현미경"),"Product selection still updates command target");
 await page.locator('#mrCommandView input[name="mr-script-format"][value="리뷰형"]').check();
 check((await page.locator('#mrCommandView .mr-generated').innerText()).includes("선택 형식: 리뷰형"),"Script format controls update output");
 await click(page,'#mrCommandView [data-copy-command]');
 await page.locator('#mrCommandView [data-copy-command][data-copy-status="success"]').waitFor({timeout:6000});
 check(true,"Command generated text is copyable");

 const mobile=await browser.newPage({viewport:{width:375,height:812},isMobile:true});
 await mobile.goto(base+"#mp=route%3Ainstagram",{waitUntil:"domcontentloaded"});
 await mobile.locator('#mrRouteView .mr-ig-tile').first().waitFor();
 check(await mobile.locator('#mrRouteView .mr-ig-tile').count()===5,"Mobile Instagram loads 5 reels");
 await checkReelAlignment(mobile,"Mobile domestic");
 const dims=await mobile.locator('#mrRouteView .mr-instagram-gallery').evaluate(el=>({width:el.getBoundingClientRect().width,display:getComputedStyle(el).display,template:getComputedStyle(el).gridTemplateColumns,columns:[...el.children].slice(0,2).map(x=>({width:x.getBoundingClientRect().width,display:getComputedStyle(x).display,column:getComputedStyle(x).gridColumn,gridArea:getComputedStyle(x).gridArea,cssWidth:getComputedStyle(x).width})),children:[...el.children].slice(0,2).map(x=>x.getBoundingClientRect().width)}));
 console.log("MOBILE GALLERY DIMENSIONS",JSON.stringify({dims,viewport:await mobile.evaluate(()=>({innerWidth,clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,media760:matchMedia("(max-width:760px)").matches}))}));await mobile.screenshot({path:"qa-v34-mobile-gallery.png",fullPage:true});
 check(dims.children.length===2&&dims.children[0]<dims.width*.7,"Mobile gallery uses two columns");
 await click(mobile,'#mrRouteView .mr-ig-tile [data-ig-detail]');
 check(await mobile.locator('#mrRouteView .mr-ig-detail').isVisible(),"Mobile reel detail opens");
 await click(mobile,'#mrRouteView .mr-ig-detail-commands [data-command="2"]');
 await mobile.locator('#mrCommandView [data-return-product]').waitFor();
 await mobile.evaluate(()=>history.back());
 await mobile.locator('#mrRouteView .mr-ig-detail').waitFor();
 check(await mobile.evaluate(()=>/^detail:/.test(history.state?.mozzipick||"")),"Mobile device back returns to original reel detail");
 await mobile.evaluate(()=>history.back());
 await mobile.locator('#mrRouteView .mr-instagram-gallery').waitFor();
 check(await mobile.evaluate(()=>history.state?.mozzipick==="route:instagram"),"Mobile device back returns to original Instagram list");
 await page.close();await mobile.close();
}
try{await run();}catch(e){errors.push(e.stack||String(e));process.exitCode=1;}finally{
 console.log(JSON.stringify({findings,errors},null,2));
 await browser.close();
}
